language: node_js

node_js:
  - "7"

os:
    - linux

dist: trusty
  
git:
  depth: 3
  submodules: false

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - ./docker-build.sh

branches:
  only:
    master

notifications:
    email:
      on_success: always
      on_failure: always
